### ISSUE TITLE
PlugUpdate fails to update

### ISSUE THREAD

**Issue by andys8** [monkoose/fzf-hoogle.vim#14]
Hi, thanks for the great extension.

I noticed the following error, when running `:PlugUpdate`.

![image](https://user-images.githubusercontent.com/13085980/103151980-61adcc80-4783-11eb-8768-b9f94590f445.png)

I think it's due to changes in the repository that lead to this behavior.

![image](https://user-images.githubusercontent.com/13085980/103151990-7c804100-4783-11eb-9f48-3977c8e5d618.png)

I think these changes were not introduced by me (the user). At least not intentionally. And this exact same scenario happened on two different machines with different operating systems.

It can be worked around with:

```
cd ~/.vim/plugged/fzf-hoogle.vim
git reset --hard
```

**Comment by monkoose** [comment]
Thank you for letting me know. I wasn't aware of it.
