### ISSUE TITLE
disable or less frequent `fzf-hoogle: `hoogle` is not installed. Plugin disabled.`

### ISSUE THREAD

**Issue by teto** [monkoose/fzf-hoogle.vim#17]
Is there a way to disable `fzf-hoogle: `hoogle` is not installed. Plugin disabled.` or maybe start the plugin only for .hs files ? I have a per project hoogle installed via nix-shell. As soon as I am out editing any file, I now get the warning (which is not helpful when editing markdown).
neovim has a vim.notify interface that can be helpful for thins kind of message

**Comment by monkoose** [comment]
Any modern plugin managers allow you to specify filetypes to load plugins only when buffer with one of this filetypes opened.
For vim-plug https://github.com/junegunn/vim-plug/blob/8fdabfba0b5a1b0616977a32d9e04b4b98a6016a/doc/plug.txt#L211

For neovim packer
https://github.com/wbthomason/packer.nvim/blob/00ec5adef58c5ff9a07f11f45903b9dbbaa1b422/doc/packer.txt#L584

Or you can do it manually with `:h :packadd`.

Other than that i'm not planning to change anything.
