### ISSUE TITLE
Reading from a local hoogle server

### ISSUE THREAD

**Issue by qwbarch** [monkoose/fzf-hoogle.vim#18]
Hi, thanks for this amazing plugin!  
Is it possible to have fzf-hoogle read from a local hoogle server? I'd like to be able to fuzzy search any of my local packages

**Comment by monkoose** [comment]
Hello. Currently do not use haskell that much. But if i do remember it correctly if you configure `hoogle` itself it should get it (with limitation that you would need to update it constantly after changes). Try to look into hoogle documentation and if it wouldn't help i will try to dig it myself.

**Comment by qwbarch** [comment]
Appreciate the response! I'll try to figure it out and then report back for any future readers looking to do the same thing

**Comment by qwbarch** [comment]
Turns out it already supports local packages, it had to do with my ``haskell.nix`` configuration.
Sorry for the redundant issue!
