### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by Avi-D-coder** [monkoose/fzf-hoogle.vim#3]
Arch Linux
NVIM v0.5.0-245-g1bfccf028
jq-1.6
Hoogle 5.0.17.3
fzf 0.20.0 (30577b0)

#### minirc.vim
```vim
call plug#begin()
Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
Plug 'monkoose/fzf-hoogle.vim'
let g:hoogle_path = '/home/user/.local/bin/hoogle'
call plug#end()
```
![ezgif-5-45af6ff12469](https://user-images.githubusercontent.com/29133776/71077639-cb999c00-2155-11ea-853f-ecb211585c78.gif)

Any ideas?

**Comment by monkoose** [comment]
Do you have last version of fzf-hoogle?
Have you generated hoogle database, with `hoogle generate` in a terminal?
Make sure if you have it with `hoogle map` in your terminal.

**Comment by Avi-D-coder** [comment]
I reinstalled fzf-hoogle before making the pr and my hoogle database is pretty recent I generated from the `lts-14.17` snapshot. Hoogle works fine from the command line

**Comment by Avi-D-coder** [comment]
My global Hoogle version was out of sync with the one I used to make the database. Hoogle 5.0.17.11.

Hoogle from the command line was working, but as it turns out the server was not.
