### ISSUE TITLE
Raw JSON in the right pane

### ISSUE THREAD

**Issue by tchoutri** [monkoose/fzf-hoogle.vim#4]
Hi! @monkoose!  I just installed fzf-hoogle.vim and upon looking up some stuff, the right pane is nothing but raw JSON:

![Screenshot from 2020-05-22 10-13-06](https://user-images.githubusercontent.com/15848443/82646456-ef857000-9c14-11ea-81e9-cba8031a2bc8.png)

System infos:
* jq 1.6
* Fedora 31
* ZSH 5.7.1
* curl 7.66.0

**Comment by monkoose** [comment]
Hello.
Can't reproduce.

Provide more info please. Your os, shell.
Problem with `bin/preview.sh` that can't process and just return json file.

I have almost the same output as you only if i change all `preview.sh` file to `eval "cat $1"`.

**Comment by tchoutri** [comment]
@monkoose I updated the issue description

**Comment by monkoose** [comment]
Test in your shell what is the output of
```
hoogle ">>=" --json -n 1 | jq -cn --stream 'fromstream(1|truncate_stream(inputs))' 2> /dev/null | jq -r '.docs'
```

Should be just doc string, not json output.

**Comment by tchoutri** [comment]
It works perfectly!
![Screenshot from 2020-05-22 19-15-22](https://user-images.githubusercontent.com/15848443/82692787-9fcc9600-9c60-11ea-83f3-5872ca4ffa62.png)

**Comment by monkoose** [comment]
Ok, i will look more into it on weekend. 

For now i'm not sure why it works in the shell, but doesn't in the fzf preview window.

**Comment by monkoose** [comment]
Sorry, can't help there. I think it's something on your side. Maybe permissions, but i'm not sure.
