### ISSUE TITLE
Would it be nice to allow "copy to clipboard"?

### ISSUE THREAD

**Issue by mingyuguo** [monkoose/fzf-hoogle.vim#8]
I added
--bind "ctrl-x:execute(echo {} | xsel -i)" to fzf parameters
it kind of works but the display is messed up unless I exit back to vim

**Comment by monkoose** [comment]
Hello.
What exactly do you want to copy? Type annotation?

**Comment by mingyuguo** [comment]
This is mostly for import convenience.

for example, after I search "windows", say, the entry I am interested in is
XMonad.Operations windows :: (WindowSet -> WindowSet) -> X ()

then I'd like my selection to be
import XMonad.Operations (windows)

Also, have you considered "change:reload" in FZF? it allows updating the list as you type

**Comment by monkoose** [comment]
> then I'd like my selection to be
import XMonad.Operations (windows)

Ah, the import statement? Hm, i think it could be done. I would consider to implement this.

> Also, have you considered "change:reload" in FZF?

Yes, I tested it. It doesn't allow some features that default filter allows, and i'm already do not remember exactly why i dropped the idea to switch to this mode, but i met some problems with implementation of some things with this mode. Currently it is easier to filter inside your initial search, when you need something more than a simple one word search.

**Comment by monkoose** [comment]
`Alt-c` to copy import statement should work with last commit.

**Comment by mingyuguo** [comment]
Thanks a lot!
