### ISSUE TITLE
sed: can't read hoogle_cache.json: No such file or directory

### ISSUE THREAD

**Issue by gvolpe** [monkoose/fzf-hoogle.vim#9]
Hi,

Thanks for working on this plugin, looks great! I was giving it a try and bumped into this issue.

![bug](https://i.imgur.com/UZOQkCw.png)

Is the `hoogle_cache.json` generated by this plugin? If so, would it be possible to configure the path for it? I'm on NixOS and the plugin installation directory is immutable by default.

**Comment by gvolpe** [comment]
Found it here: https://github.com/monkoose/fzf-hoogle.vim/blob/master/autoload/hoogle.vim#L29

If you're okay with it, I can try to make a PR.

**Comment by bogdan-manole** [comment]
> Hi,
> 
> Thanks for working on this plugin, looks great! I was giving it a try and bumped into this issue.
> 
> ![bug]
> 
> Is the `hoogle_cache.json` generated by this plugin? If so, would it be possible to configure the path for it? I'm on NixOS and the plugin installation directory is immutable by default.

same problem, it worked until i migrate few days ago to nix home-manager from a standard Plug setup
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/3176255/100802097-9737f200-3431-11eb-8419-f61a6bc0ba2f.png">

**Comment by monkoose** [comment]
Hello.
Yes, maybe was my mistake to think that user has access to plugin location, so i removed the option to configure cache file location some time ago.
Will fix this.

**Comment by gvolpe** [comment]
Thanks @monkoose !
